Варіант №6

In [21]:
import numpy as np
import random

In [72]:
# Завдання 1 Створіть одновимірний масив (вектор) з перших 10-ти додатних парних чисел та виведіть його значення.

array = [i for i in range(2,11,2)]
print("Масив :", array)


Масив : [2, 4, 6, 8, 10]


In [19]:
# Завдання 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його сумою кожного числа та його попереднього, починаючи з 1, та виведіть його значення.

v = 1
matrix = []
for i in range(3):
    row = []
    for j in range(3):
        nv = v + (v - 1)
        row.append(nv)
        v += 1
    matrix.append(row)
for row in matrix:
    print(row)


[1, 3, 5]
[7, 9, 11]
[13, 15, 17]


In [29]:
# Завдання 3 Створіть масив розміром 2x3, заповніть його випадковими цілими числами в діапазоні від -1 до 1 та виведіть його значення.

matrix1 = np.random.randint(-1, 1, size =(2,3))
print(matrix1)

[[ 0  0  0]
 [-1  0 -1]]


In [91]:
# Завдання 4 Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

matrix2 = np.random.random( size =(5,5))
print(matrix2)
row_sums = matrix2.sum(axis = 1)
print("\n", row_sums.reshape(-1,1))

[[0.17122534 0.122369   0.93565149 0.17953158 0.82580722]
 [0.56495618 0.71669163 0.86640918 0.29014365 0.49406598]
 [0.85206895 0.74466332 0.81898302 0.86727489 0.52987794]
 [0.58762639 0.04262029 0.79917106 0.8581649  0.23421679]
 [0.26656177 0.34882643 0.20319133 0.52517589 0.81720929]]

 [[2.23458463]
 [2.93226661]
 [3.81286812]
 [2.52179942]
 [2.16096472]]


In [90]:
# Завдання 5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими дійсними числами від 0 до 1 та виконайте на них поелементні операції додавання, віднімання та множення.

b = np.random.random( size = 5)
c = np.random.random( size = 5)
print("b = ", b, "c = ", c)

sum = b + c
sub = b - c
mult = b * c
print("+ = ", sum, "\n- =", sub, "\n* = ", mult)

b =  [0.93875277 0.31705086 0.13293233 0.81379967 0.72034507] c =  [0.18545116 0.05077208 0.79793064 0.74319662 0.1121069 ]
+ =  [1.12420393 0.36782294 0.93086297 1.5569963  0.83245197] 
- = [ 0.75330162  0.26627878 -0.6649983   0.07060305  0.60823817] 
* =  [0.17409279 0.01609733 0.10607078 0.60481317 0.08075566]


In [89]:
# Завдання 6 Створіть дві матриці 3x3, заповніть їх довільними дійсними числами від 5 до 30 та знайдіть їх добуток.

matrix1 = np.random.randint(5, 30, size = (3, 3))
matrix2 = np.random.randint(5, 31, size = (3, 3))
print("1 матриця", "\n", matrix1, "\n2 матриця", "\n", matrix2)
dob = np.dot(matrix1, matrix2)
print("добуток матриць = ", "\n", dob)


1 матриця 
 [[ 9 19  9]
 [26 10 17]
 [24 27 10]] 
2 матриця 
 [[11 19 23]
 [14  8 21]
 [12 24 21]]
добуток матриць =  
 [[ 473  539  795]
 [ 630  982 1165]
 [ 762  912 1329]]


In [70]:
# Завдання 7 Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

matrix1 = np.random.randint(1, 6, size = (2, 3))
matrix2 = np.random.randint(1, 6, size = (3, 4))
print("1 матриця", "\n", matrix1, "\n2 матриця", "\n", matrix2)
dob1 = np.dot(matrix1, matrix2)
print("добуток матриць = ", "\n", dob1)

1 матриця 
 [[5 2 4]
 [2 3 2]] 
2 матриця 
 [[5 4 1 1]
 [5 3 5 5]
 [3 2 2 2]]
добуток матриць =  
 [[47 34 23 23]
 [31 21 21 21]]


In [69]:
# Завдання 8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю.

matrix = np.random.randint(1, 9, size = (3, 3))
print("матриця", "\n", matrix)
matrix_inv = np.linalg.inv(matrix)
print("обернена матриця", "\n", matrix_inv)

матриця 
 [[8 3 4]
 [6 7 5]
 [1 5 2]]
обернена матриця 
 [[ 0.64705882 -0.82352941  0.76470588]
 [ 0.41176471 -0.70588235  0.94117647]
 [-1.35294118  2.17647059 -2.23529412]]


In [86]:
# Завдання 9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

matrix = np.random.random(size = (4, 4))
print("матриця", "\n", matrix)
print("транспонована матриця", "\n", matrix.T)

матриця 
 [[0.29464681 0.15230516 0.98470537 0.34523414]
 [0.39897762 0.31561913 0.81512596 0.70244257]
 [0.00588958 0.31845804 0.79428156 0.91201392]
 [0.48654059 0.92096896 0.36457303 0.49075234]]
транспонована матриця 
 [[0.29464681 0.39897762 0.00588958 0.48654059]
 [0.15230516 0.31561913 0.31845804 0.92096896]
 [0.98470537 0.81512596 0.79428156 0.36457303]
 [0.34523414 0.70244257 0.91201392 0.49075234]]


In [85]:
# Завдання 10 Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, знайдіть добуток матриці на вектор.

matrix = np.random.random(size = (3, 4))
v = np.random.random(size = (4, 1))
print("матриця", "\n", matrix)
print("масив = ", "\n", v)
dob = np.dot(matrix, v)
print("добуток матриця на вектор", "\n", dob)

матриця 
 [[0.53029208 0.72562465 0.93748789 0.98760415]
 [0.97295479 0.0031655  0.84103747 0.10488846]
 [0.05521364 0.20760452 0.02909443 0.1474204 ]]
масив =  
 [[0.23350237]
 [0.8702248 ]
 [0.2115477 ]
 [0.59781249]]
добуток матриця на вектор 
 [[1.54400653]
 [0.47056512]
 [0.28783974]]


In [92]:
# Завдання 11 Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

matrix = np.random.randint(1, 11, size = (2, 3))
v = np.random.random(size = (3, 1))
print("матриця", "\n", matrix)
print("масив = ", "\n", v)
dob = np.dot(matrix, v)
print("добуток матриця на вектор", "\n", dob)

матриця 
 [[10  5  4]
 [ 3  5  5]]
масив =  
 [[0.5299942 ]
 [0.22325399]
 [0.25739785]]
добуток матриця на вектор 
 [[7.44580332]
 [3.99324179]]


In [93]:
# Завдання 12 Створіть дві матриці розміром 7x7, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

matrix1 = np.random.randint(1, 11, size=(7, 7))
matrix2 = np.random.randint(1, 11, size=(7, 7))
print("1 матриця", "\n", matrix1, "\n2 матриця", "\n", matrix2)
diff = matrix1 - matrix2
print("різниця", "\n", diff)


1 матриця 
 [[ 7  9  5 10  6  8  8]
 [ 6  5  7  2  6  5  9]
 [ 9  2  4  3  3  1  4]
 [ 8  5  2  9  8  4  3]
 [ 6  9  5 10  3  6  8]
 [ 4  5  1  3  7  4  4]
 [ 6 10  2  4  9  5  1]] 
2 матриця 
 [[ 8  3  4  2  4  3  1]
 [ 3  6  2  3  6  9  9]
 [ 9  4  4  1  2  2  9]
 [ 5 10  9  2 10  6  9]
 [ 2  6  1  3 10  8  7]
 [ 2  9 10  3  1  9  2]
 [ 1  8  9 10  2  8  6]]
різниця 
 [[-1  6  1  8  2  5  7]
 [ 3 -1  5 -1  0 -4  0]
 [ 0 -2  0  2  1 -1 -5]
 [ 3 -5 -7  7 -2 -2 -6]
 [ 4  3  4  7 -7 -2  1]
 [ 2 -4 -9  0  6 -5  2]
 [ 5  2 -7 -6  7 -3 -5]]


In [95]:
# Завдання 13 Створіть дві матриці розміром 7x7, заповніть їх випадковими цілими числами в діапазоні від -10 до 10 та знайдіть суму їх елементів.

matrix1 = np.random.randint(-10, 11, size=(7, 7))
matrix2 = np.random.randint(-10, 11, size=(7, 7))
sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)
total_sum = sum_matrix1 + sum_matrix2
print("1 матриця", "\n", matrix1, "\n2 матриця", "\n", matrix2)
print("1 матриця сума", "\n", sum_matrix1, "\n2 матриця сума", "\n", sum_matrix2)
print("загальна сума = ", total_sum)

1 матриця 
 [[  3  -2   0  -7 -10  -8  -6]
 [-10   9   3  -2  -6  -9   9]
 [ -4   7   7 -10  -3   0   4]
 [ -5  -6  -5   7  -5  -7   3]
 [  8  -5  -4   2   2   4   8]
 [ 10   1   9   4  10  -5  10]
 [  7   1   0  -1   1  -8  -3]] 
2 матриця 
 [[  0 -10  -5  -3   9   6   1]
 [  9   4  -8  -7  -3  -1   9]
 [ -9  -2  -9   7 -10   4  -5]
 [ -3  -2  -8  10 -10   8   3]
 [  8   6   2  -4   5   9   6]
 [  5   5   5  -4  -6  -1  -8]
 [  7   4   4  -3  -1   4   8]]
1 матриця сума 
 -2 
2 матриця сума 
 26
загальна сума =  24


In [96]:
# Завдання 14 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть середнє арифметичне значення елементів матриці.

matrix = np.random.randint(1, 11, size=(3, 3))
print("матриця", "\n", matrix)
mean_value = np.mean(matrix)
print("середнє арифметичне значення = ", mean_value)

матриця 
 [[8 4 2]
 [2 1 8]
 [6 1 2]]
середнє арифметичне значення =  3.7777777777777777


In [97]:
# Завдання 15 Створіть матрицю розміром 8x8, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить найменший елемент у кожному рядку матриці.

matrix = np.random.uniform(-1, 1, size=(8, 8))
print("матриця", "\n", matrix)
min_e = np.min(matrix, axis=1)
print("найменший елемент у кожному рядку", "\n", min_e)


матриця 
 [[ 0.8127053   0.17154534 -0.73580041 -0.3487427   0.01682795  0.78194199
  -0.79814717  0.03284003]
 [ 0.21484238 -0.86130408  0.80845251  0.39878411 -0.76232838  0.81110752
   0.11269685 -0.57920654]
 [-0.67268766  0.38321639  0.4989487   0.77181869 -0.15671581 -0.38665891
  -0.91235742  0.60236356]
 [ 0.15021719  0.71068154 -0.99387751 -0.61599378  0.88038349  0.36155619
   0.17200712 -0.2120865 ]
 [-0.90557321 -0.00998773 -0.06373481  0.02786363  0.90657108 -0.91277755
  -0.90464104  0.06589766]
 [ 0.47561484 -0.99426372  0.24511089 -0.9449358  -0.47531569  0.06696322
  -0.70451025 -0.5632548 ]
 [ 0.88918743 -0.90276136  0.4474684   0.84024134  0.31963987  0.1183929
  -0.70396346  0.05083051]
 [ 0.29433279  0.34591348  0.20857289  0.21866697  0.42360919  0.79229816
   0.4802104  -0.27133483]]
найменший елемент у кожному рядку 
 [-0.79814717 -0.86130408 -0.91235742 -0.99387751 -0.91277755 -0.99426372
 -0.90276136 -0.27133483]
